- name: "Cleanup: Generate deployment_prefix"
  set_fact:
    deployment_prefix: '{{ deployment_name | upper | regex_replace("\-","") }}'
    servers: "{{ lookup('file', cloud_dir + '/lun-wwn.json') | from_json| json_query('keys(@)') }}"

- name: Cleanup 3PAR storage
  include_tasks: 3par.yml
  vars:
    delete_3par_luns: yes
  tags:
    - 3par

- name: Cleanup Unity storage
  include_tasks: unity.yml
  vars:
    delete_unity_luns: yes
  tags:
    - unity