---
- hosts: '{{ group_to_update }}'
  gather_facts: no
  vars:
    ansible_ssh_pass: '{{ ssh_password }}'
  tasks:
    - name: "Add {{ user }} user's public key to authorized_keys file"
      authorized_key:
        user: '{{ user }}'
        state: present
        key: '{{ lookup("file","awx_ssh.pub") }}'