apiVersion: v1
kind: ConfigMap
metadata:
  name: webcfg
data:
  index.html: |
     <h1> My test page! </h1>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: webroot
          configMap:
            name: webcfg
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - name: webroot
            mountPath: /usr/share/nginx/html
        ports:
          - containerPort:  80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testingress
spec:
  rules:
  - host: "ieatenmc0.athtem.eei.ericsson.se"
    http:
      paths: 
      - pathType: Prefix
        path: /
        backend:
          service:
            name: nginx-service
            port:
              number: 80
