- name: Run playbook to create etcd-certs secret in the monitoring namespace
  block:
    - name: Find CCD directory
      find:
        path: /var/
        file_type: directory
        use_regex: yes
        recurse: yes
        patterns:
          - '^eccd'
      register: find_ccd_install_dir

    - name: Save path to CCD ansible/erikube directory
      set_fact:
        eccd_install_dir: "{{ find_ccd_install_dir.files | map(attribute='path') | first }}/ansible/erikube"

    - name: Copy create-monitoring-secret.yml playbook
      copy:
        src: create-monitoring-secret.yml
        dest: '{{ eccd_install_dir }}'

    - name: Run create-monitoring-secret.yml playbook
      shell: "export ANSIBLE_LOG_PATH=$(date '+%Y%m%d%H%M%S')-create-monitoring-secret.log; ansible-playbook -i ~/ccd_inventory.yml create-monitoring-secret.yml"
      args:
        chdir: '{{ eccd_install_dir }}'

  delegate_to: kickstart
  run_once: true
