# This is from the playbooks/victoria-metrics-pm-deploy.yml playbook
# Everything has been removed except the tasks necessary to create
# the etcd-certs secret in the monitoring namespace. This secret is 
# required to deploy de-cni monitoring
- name: Gather facts as non root
  hosts: master[0]
  gather_facts: yes

- name: Deploy vmagent client certificate for etcd
  hosts: master[0]
  vars:
    etcd_peers: "{{ groups.etcd | default([], true) }}"
    etcd_ca_host: "{{ groups.etcd.0 }}"
  roles:
    - role: victoria-metrics