apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.rwx.loaddirName }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.global.loaddirSize }}
  storageClassName: {{ .Values.global.storageClass | quote }}
